/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as UsersCreateRouteImport } from './routes/users/create'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as LocationsCreateRouteImport } from './routes/locations/create'
import { Route as LocationsIdRouteImport } from './routes/locations/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCreateRoute = LocationsCreateRouteImport.update({
  id: '/locations/create',
  path: '/locations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/create': typeof LocationsCreateRoute
  '/users/$id': typeof UsersIdRoute
  '/users/create': typeof UsersCreateRoute
  '/locations': typeof LocationsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/create': typeof LocationsCreateRoute
  '/users/$id': typeof UsersIdRoute
  '/users/create': typeof UsersCreateRoute
  '/locations': typeof LocationsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/create': typeof LocationsCreateRoute
  '/users/$id': typeof UsersIdRoute
  '/users/create': typeof UsersCreateRoute
  '/locations/': typeof LocationsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/locations/$id'
    | '/locations/create'
    | '/users/$id'
    | '/users/create'
    | '/locations'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/locations/$id'
    | '/locations/create'
    | '/users/$id'
    | '/users/create'
    | '/locations'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/locations/$id'
    | '/locations/create'
    | '/users/$id'
    | '/users/create'
    | '/locations/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsIdRoute: typeof LocationsIdRoute
  LocationsCreateRoute: typeof LocationsCreateRoute
  UsersIdRoute: typeof UsersIdRoute
  UsersCreateRoute: typeof UsersCreateRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/create': {
      id: '/locations/create'
      path: '/locations/create'
      fullPath: '/locations/create'
      preLoaderRoute: typeof LocationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsIdRoute: LocationsIdRoute,
  LocationsCreateRoute: LocationsCreateRoute,
  UsersIdRoute: UsersIdRoute,
  UsersCreateRoute: UsersCreateRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
